# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "pg_enum"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["BradfordW", "Fredrik Roos"]
  s.date = "2013-03-17"
  s.description = "Adds native enum support to the Rails3 ActiveRecord PostgreSQL adapter"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/pg_enum.rb",
    "lib/pg_enum/active_record.rb",
    "pg_enum.gemspec",
    "rails/init.rb"
  ]
  s.homepage = "http://github.com/fredrikroos/pg_enum"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Adds native enum support to the Rails3 ActiveRecord PostgreSQL adapter"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

